/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wanderer_above_the_sea_of_fog.glb --resolution 4096 --keepmaterials --types
Author: betocarrillo (https://sketchfab.com/betocarrillo)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/wanderer-above-the-sea-of-fog-518e605e9b734c86aab5bc22f9797f77
Title: Wanderer above the sea of fog
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
  }
  materials: {
    brush_Ink: THREE.MeshBasicMaterial
    brush_ThickPaint: THREE.MeshBasicMaterial
    brush_Marker: THREE.MeshBasicMaterial
    ['media_image_Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog']: THREE.MeshBasicMaterial
  }
}

export function Wanderer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/wanderer_above_the_sea_of_fog.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.brush_Ink} position={[-0.734, -3.723, -0.712]} scale={10.149} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.brush_ThickPaint} position={[-14.931, -7.696, 24.674]} scale={107.99} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.brush_Marker} position={[-1.459, -2.494, -0.618]} scale={0.175} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['media_image_Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog']} position={[-7.72, 2.051, 11.359]} rotation={[0.082, -0.72, 0.054]} scale={1.818} />
    </group>
  )
}

useGLTF.preload('models/wanderer_above_the_sea_of_fog.glb')
